### PR TITLE
Added initial database schema design

### PR DESCRIPTION
**Pull request by tanner-g**
- Need group feedback on types selected, names for fields in each table, and suggestions on what modifications/changes should happen.

### CODE REVIEW

**Comment by JasonPuglisi** [comment]
Looks pretty good. I would change `userID` and `contentID` to `CHAR(16)` so we can create GUIDs for them and store as efficiently as possible (more secure than using int and auto incrementing too). Would also add a `logID CHAR(16)` and `date TIMESTAMP` for logs. Do we want to add `userID` to logs as well so we can audit specific user actions?

**Comment by tanner-g** [comment]
I agree with userID and contentID change and timestamp type. Making those changes now. As for userID on logs, I was thinking about that. If its a bad login attempt, we won't have a userID to match. But for other site access user x goes to page y, we could follow that.

**Comment by tanner-g** [comment]
we could use attempted username for bad login

**Comment by JasonPuglisi** [comment]
Yeah if we do userID we could just leave the field null when there's no authorized user, and MySQL won't have a problem with that. Maybe we can put the failed login username and IP in the log message itself?

**Comment by tanner-g** [comment]
adding ip field

**Comment by JasonPuglisi** [comment]
Can we add a sessions table with session GUID, expiration timestamp, user GUID, and IP?

**Pull request merged**
